[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "14k4c2Pff5F46qMUznH7crXvcCQm6Tq7BYEM25fTgMWV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
